#####################################
# action_noise: 0 ~ 20
# mass: 0 ~ 3
# damping: 0 ~ 20
default:
  system_params:
    {
      action_noise_0: [[0.5, 1.5]],
      action_noise_1: [[0.5, 1.5]],
      action_noise_2: [[0.5, 1.5]],
      action_noise_3: [[0.5, 1.5]],
      action_noise_4: [[0.5, 1.5]],
      action_noise_5: [[0.5, 1.5]],
      action_noise_6: [[0.5, 1.5]],
      action_noise_7: [[0.5, 1.5]],
      action_noise_8: [[0.5, 1.5]],
      action_noise_9: [[0.5, 1.5]],
      action_noise_10: [[0.5, 1.5]],
      action_noise_11: [[0.5, 1.5]],
      action_noise_12: [[0.5, 1.5]],
      action_noise_13: [[0.5, 1.5]],
      action_noise_14: [[0.5, 1.5]],
      action_noise_15: [[0.5, 1.5]],
      action_noise_16: [[0.5, 1.5]],
      action_noise_17: [[0.5, 1.5]],
      action_noise_18: [[0.5, 1.5]],
      action_noise_19: [[0.5, 1.5]],
      action_noise_20: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
mass:
  system_params:
    {
      mass_0: [[0.5, 1.5]],
      mass_1: [[0.5, 1.5]],
      mass_2: [[0.5, 1.5]],
      mass_3: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
