#####################################
# action_noise: 0
# mass: 0 ~ 2
default:
  system_params:
    {
      action_noise_0: [[-1.5, -0.5], [0.5, 1.5]],
    }
  context_samples:
    None
#####################################
mass:
  system_params:
    {
      mass_0: [[0.5, 1.5]],
      mass_1: [[0.5, 1.5]],
      mass_2: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
