#####################################
# action_noise: 0 ~ 7
# mass: 0 ~ 3
# damping: 0 ~ 7
default:
  system_params:
    {
      action_noise_0: [[0.5, 1.5]],
      action_noise_1: [[0.5, 1.5]],
      action_noise_2: [[0.5, 1.5]],
      action_noise_3: [[0.5, 1.5]],
      action_noise_4: [[0.5, 1.5]],
      action_noise_5: [[0.5, 1.5]],
      action_noise_6: [[0.5, 1.5]],
      action_noise_7: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
mass:
  system_params:
    {
      mass_0: [[0.5, 1.5]],
      mass_1: [[0.5, 1.5]],
      mass_2: [[0.5, 1.5]],
      mass_3: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
crippled_1:
  system_params:
    [
      action_noise_0,
      action_noise_1,
      action_noise_2,
      action_noise_3,
      action_noise_4,
      action_noise_5,
      action_noise_6,
      action_noise_7,
    ]
  context_samples:
    "list(set([tuple(1 if i != j*2 and i != j*2+1 else -1 for i in range(8)) for j in range(4)]))"
#####################################
crippled_2:
  system_params:
    [
      action_noise_0,
      action_noise_1,
      action_noise_2,
      action_noise_3,
      action_noise_4,
      action_noise_5,
      action_noise_6,
      action_noise_7,
    ]
  context_samples:
    "list(set([tuple(1 if i not in [j*2, (j*2+k*2)%8, j*2+1, (j*2+1+k*2)%8] else -1 for i in range(8)) for j in range(4) for k in range(1,4)]))"
#####################################
