#####################################
# action_noise: 0 ~ 11
# mass: 0 ~ 3
# damping: 0 ~ 11
default:
  system_params:
    {
      action_noise_0: [[0.5, 1.5]],
      action_noise_1: [[0.5, 1.5]],
      action_noise_2: [[0.5, 1.5]],
      action_noise_3: [[0.5, 1.5]],
      action_noise_4: [[0.5, 1.5]],
      action_noise_5: [[0.5, 1.5]],
      action_noise_6: [[0.5, 1.5]],
      action_noise_7: [[0.5, 1.5]],
      action_noise_8: [[0.5, 1.5]],
      action_noise_9: [[0.5, 1.5]],
      action_noise_10: [[0.5, 1.5]],
      action_noise_11: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
mass:
  system_params:
    {
      mass_0: [[0.5, 1.5]],
      mass_1: [[0.5, 1.5]],
      mass_2: [[0.5, 1.5]],
      mass_3: [[0.5, 1.5]],
      # damping_0: [[0.5, 1.5]],
      # damping_1: [[0.5, 1.5]],
      # damping_2: [[0.5, 1.5]],
      # damping_3: [[0.5, 1.5]],
      # damping_4: [[0.5, 1.5]],
      # damping_5: [[0.5, 1.5]],
      # damping_6: [[0.5, 1.5]],
      # damping_7: [[0.5, 1.5]],
      # damping_8: [[0.5, 1.5]],
      # damping_9: [[0.5, 1.5]],
      # damping_10: [[0.5, 1.5]],
      # damping_11: [[0.5, 1.5]],
    }
  context_samples:
    None
#####################################
